module SimpleRRD
  class CDef < Command
		# CDEF:vname=RPN expression
		#	
		# This command creates a new set of data points (in memory only, not in
		# the RRD file) out of one or more other data series. The RPN
		# instructions are used to evaluate a mathematical function on each data
		# point. The resulting vname can then be used further on in the script,
		# just as if it were generated by a DEF instruction.  
		#  
		#   Example: "CDEF:mydatabits=mydata,8,*"
		
		include VName
		include RPNExpressionAttribute
    include HashToMethods

		def initialize(opts = {})
			call_hash_methods(opts)
		end
		
		def allowed_functions 
			CDEF_FUNCTIONS
		end

    def definition
      raise "No expression defined" unless rpn_expression
      return "CDEF:#{vname}=#{expression_string}"
    end
  end
end
